### ISSUE TITLE
issue with checkupates

### ISSUE THREAD

**Issue by cooldog14** [MagnuSiwy/dotfilesQtile#1]
Hi, really like the dotfiles, sadly, I cannot log in succesfully with them, qtile crash at launch and the log files give me this : 

```
2024-02-08 09:04:03,845 ERROR libqtile base.py:on_done():L857 Failed to reschedule timer for checkupdates.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 851, in on_done
    self.update(result)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 755, in update
    old_width = self.layout.width
                ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 421, in width
    return self.layout.get_pixel_size()[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/pangocffi.py", line 137, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2024-02-08 09:04:03,846 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
```

I am pretty sure it is related to the arch update widget. when I delete lines related to the arch update widget in the bar config I get new errors...

Weird thing is, I launch succesfully qtile with the default config, then replace the default config with the dotfiles and everything works.

**Comment by MagnuSiwy** [comment]
Hey, this is a built in widget with which I haven't had any problems before. Did you install the pacman-contrib package? If that doesn't work you could try to change the "Arch_checkupdates" to just "Arch" in distro setting in the CheckUpdates widget. Then we'll know if it is connected to the checkupdates script or something else. Could you show me the errors that appear after deleting checkupdates widget? If that doesn't work, I'm gonna try to take a more in depth look.

Also was it just a clear arch/qtile install? I provided an install.sh script with all of the packages that you need to run the dotfiles the same way I do.

**Comment by cooldog14** [comment]
My bad, it was the nm-applet that I put in the autostart.sh that messed everything lol
